// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBeodOsRgyLZmD_9tJTRtOH2Tc8UaoZWy0',
    appId: '1:661562707949:web:733d013c8cbffb0a1fe1e4',
    messagingSenderId: '661562707949',
    projectId: 'proyecto-iseneca-9f849',
    authDomain: 'proyecto-iseneca-9f849.firebaseapp.com',
    storageBucket: 'proyecto-iseneca-9f849.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBv7W3YpRGGBoW0vOCMGC1c-KQbA4IivEA',
    appId: '1:661562707949:android:a87b2091e4faffa41fe1e4',
    messagingSenderId: '661562707949',
    projectId: 'proyecto-iseneca-9f849',
    storageBucket: 'proyecto-iseneca-9f849.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD1KdFLOfVQ-I2KIUWAh3BPKBF9_Cxnz0U',
    appId: '1:661562707949:ios:bcef580f5446bab81fe1e4',
    messagingSenderId: '661562707949',
    projectId: 'proyecto-iseneca-9f849',
    storageBucket: 'proyecto-iseneca-9f849.firebasestorage.app',
    iosBundleId: 'com.example.iseneca',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD1KdFLOfVQ-I2KIUWAh3BPKBF9_Cxnz0U',
    appId: '1:661562707949:ios:bcef580f5446bab81fe1e4',
    messagingSenderId: '661562707949',
    projectId: 'proyecto-iseneca-9f849',
    storageBucket: 'proyecto-iseneca-9f849.firebasestorage.app',
    iosBundleId: 'com.example.iseneca',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBeodOsRgyLZmD_9tJTRtOH2Tc8UaoZWy0',
    appId: '1:661562707949:web:65d429361f095ea81fe1e4',
    messagingSenderId: '661562707949',
    projectId: 'proyecto-iseneca-9f849',
    authDomain: 'proyecto-iseneca-9f849.firebaseapp.com',
    storageBucket: 'proyecto-iseneca-9f849.firebasestorage.app',
  );
}
